<?php

// $Id$

function cnf_corporate_menu() {
  $items['corporate'] = array(
		'title' => t(''),
		'page callback' => 'corporate',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
	
	$items['press_coverage'] = array(
		'title' => t('Press Coverage'),
		'description' => 'Press Coverage',
		'page callback' => 'press_coverage',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);   
	return $items;
}

function corporate() {
	global $base_url;
	drupal_goto($base_url.'/corporate/press_coverage');
}

function press_coverage() {
	global $base_url;
	$page = $_GET['page'];
	$start = $_GET['page'] * ITEM_PER_PAGE;
	$archive_year = arg(1);
	if (empty($archive_year)) {
		$query = "SELECT YEAR(FROM_UNIXTIME(field_press_coverate_date_value) + INTERVAL 12 HOUR) as year "
							. "FROM node a, field_data_field_press_coverate_date b "
							. "WHERE a.nid = b.entity_id AND type='press_coverage' GROUP BY year ORDER by year DESC LIMIT 1";
		$result = db_query($query);
		foreach ($result as $archive) {
			$archive_year = $archive->year;
		}
	}
	
	$query = "SELECT nid  FROM node a, field_data_field_press_coverate_date b
						WHERE a.nid = b.entity_id AND type='press_coverage' AND YEAR(FROM_UNIXTIME(field_press_coverate_date_value) + INTERVAL 12 HOUR)=".$archive_year." ORDER BY field_press_coverate_date_value DESC";
	//$query_total = "SELECT count(nid) as total FROM node a, field_data_field_press_coverate_date b
	//					WHERE a.nid = b.entity_id AND type='press_coverage' ORDER BY field_press_coverate_date_value DESC"; 
	
	$result = db_query_range($query, $start, ITEM_PER_PAGE);
	foreach ($result as $news) {
		 $node_nids[] = $news->nid;
	}
	
	// paging
	//$total = db_query($query_total)->fetchField();
	$total = db_query($query)->rowCount();
	pager_default_initialize($total, ITEM_PER_PAGE);
		
	$content['press_coverage'] = node_load_multiple($node_nids);
	return theme('cnf_press_coverage', array('content' => $content));
}

/**
 * Implements hook_theme().
 */
function cnf_corporate_theme($existing, $type, $theme, $path) {
	return array(
		'cnf_press_coverage' => array(
			'variables' => array('content' => NULL),
			'template' => 'cnf_press_coverage', // place you file in 'theme' folder of you module folder
			'path' => drupal_get_path('module', 'cnf_corporate')
		)
	);
}

function cnf_corporate_block_info() {
  $blocks['corporate_menu'] = array('info' => t('Corporate Menu'));
  $blocks['press_coverage_archive'] = array('info' => t('Press Coverage Archive'));
  return $blocks;
}

function cnf_corporate_block_view($delta='') {
  $block = array();
  switch ($delta) {
		case 'corporate_menu':
      $block['subject'] = t('');
      $block['content'] = _corporate_menu();
      break;
    case 'press_coverage_archive':
      $block['subject'] = t('');
      $block['content'] = _press_coverage_archive();
      break;
  }
  return $block;
}

function _corporate_menu() {
	global $base_url;
	$arg0 = arg(0);
	$arg1 = arg(1);
	if ($arg0 == 'corporate' || ($arg0 == 'node' && isset($arg1))) {
		$query = "SELECT nid, title FROM node WHERE type='corporate'";
		$result = db_query($query);
		$output = '<ul class="sidebar-menu">';
		foreach($result as $row) {
			$alias = drupal_lookup_path('alias',"node/".$row->nid);
			$active1 = '';
			if ($arg1 == $row->nid) $active1 = 'class="active"';
				$output .= '<li '.$active1.'><a title="'.$row->title.'" href="'.$base_url.'/'.$alias.'">'.$row->title.'</a></li>';
		}
		//if ($arg0 == 'corporate' && $arg1 == 'press_coverage') $active2 = 'class="active"';
		//$output .= '<li '.$active2.'><a title="Press Coverage" href="'.$base_url.'/corporate/press_coverage">Press Coverage</a></li>';
		$output .= '</ul>';
		return $output;
	}
}

function _press_coverage_archive(){
	global $base_url;
	$arg0 = arg(0);
	if ($arg0 == 'press_coverage') {
		$archive_year = arg(1);

		if (empty($archive_year)) {
			$query = "SELECT YEAR(FROM_UNIXTIME(field_press_coverate_date_value) + INTERVAL 12 HOUR) as year "
								. "FROM node a, field_data_field_press_coverate_date b "
								. "WHERE a.nid = b.entity_id AND type='press_coverage' GROUP BY year ORDER by year DESC LIMIT 1";
			$result = db_query($query);
			foreach ($result as $archive) {
				$archive_year = $archive->year;
			}
		}

		$query = "SELECT YEAR(FROM_UNIXTIME(field_press_coverate_date_value) + INTERVAL 12 HOUR) as year "
						. "FROM node a, field_data_field_press_coverate_date b "
						. "WHERE a.nid = b.entity_id AND type='press_coverage' GROUP BY year ORDER by year DESC LIMIT 12";
		$result = db_query($query);
		$output = '<h4>Archives</h4> <ul class="hover-effect archives">';
		foreach ($result as $archive) {
			if ($archive_year == $archive->year) $active = 'class="active"';
			else $active = '';
			$output .= '<li '.$active.'>'
				. '<a href="'.$base_url.'/press_coverage/'.$archive->year.'">'.$archive->year.'</a></li>';
		}
		$output .= '</ul>';

		return $output;
	}
}

?>
