<?php

// $Id$
global $base_url;
define("PATH_TO_FILE", $base_url."/sites/default/files/");
define("ITEM_PER_PAGE", 12);

function cnf_custom_function_menu() {
	$items['subscribe'] = array(
		'title' => t('Subscribe'),
		'description' => 'subscribe',
		'page callback' => 'subscribe',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
        
	return $items;
}

/**
 * Implements hook_theme().
 */
function cnf_custom_function_theme($existing, $type, $theme, $path) {
    return array(
      'address_block' => array(
        'variables' => array('content' => NULL),
        'template' => 'address_block', // place you file in 'theme' folder of you module folder
        'path' => drupal_get_path('module', 'cnf_custom_function')
      )
    );
}

function cnf_custom_function_block_info() {
  $blocks['address_block'] = array('info' => t('CnF Address'));
  return $blocks;
}

function cnf_custom_function_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'address_block':
      $block['subject'] = t('');
      $block['content'] = _address_block();
      break;
  }
  return $block;
}

function _address_block() {
	global $base_url;
		$arg0 = arg(0);
		if ($arg0 == 'contact' || $arg0 == 'store-locator') {
			return theme('address_block');
		}
}

function get_product_brand ($vocabulary) {
	$vacabulary = taxonomy_vocabulary_machine_name_load($vocabulary.'_brand');
	$tree = taxonomy_get_tree($vacabulary->vid);
	return $tree;
}

function get_product_category ($vocabulary) {
	$vacabulary = taxonomy_vocabulary_machine_name_load($vocabulary.'_category');
	$tree = taxonomy_get_tree($vacabulary->vid);
	return $tree;
}

function subscribe() {
	global $base_url;
	$output = '';
	$email = $_POST['email'];
	if (empty($email)) {
		drupal_set_message('Email cannot be empty', 'error');
		return $output;
	}
	$tid = 1;
	$subscribe = simplenews_subscribe_user($email, 1, FALSE);
	drupal_set_message('Your email has been submitted successfully', 'notice');
	//drupal_goto($base_url.'/subscribe');
	return $output;
}

function breadcrumb() {
	global $base_url;
	$arg0 = arg(0);
	$arg1 = arg(1);
	$output = '<li><a href="'.$base_url.'">Home</a></li>';
	if (isset($arg0) && empty($arg1)) {
		$arg0 = str_replace('_', ' ', $arg0);
		$arg0 = ucwords($arg0); 
		$output .= '<li class="active">'.$arg0.'</li>';
	}
	if (isset($arg0) && isset($arg1)) {
		if ($arg0 == 'node') {
			$node = node_load($arg1);
			$title = $node->title;
			$parent = 'Corporate';
		} else if ($arg0 == 'fragrance' || $arg0 == 'skin_care' || $arg0 == 'make_up') {
			$arg0 = str_replace('_', ' ', $arg0);
			$arg0 = ucwords($arg0);
			$parent = $arg0;
			$category = taxonomy_term_load($arg1);
			$title = $category->name;
		} else if ($arg0 == 'corporate') {
			$parent = ucwords($arg0);
			$arg1 = str_replace('_', ' ', $arg1);
			$arg1 = ucwords($arg1);
			$title = $arg1;
		}
		$output .= '<li><a href="#">'.$parent.'</a></li><li class="active">'.$title.'</li>';
	}
	return $output;
}

function top_menu() {
	global $base_url;
	$arg0 = arg(0);
	$arg1 = arg(1);
	$output = '';
	$top_menu = menu_load_links('menu-top-menu');
	
	//print "<pre>".print_r($top_menu, true)."</pre>"; exit;
	foreach($top_menu as $menu) {
		$active = '';
		if ($arg0 == $menu['link_path']) {
			$active = 'active';
		} 
		else if ($arg0 == 'node' && $arg1 == '' && strtolower($menu['link_title']) == 'home') $active = 'active';
		else if ($arg0 == 'node' && isset($arg1) && strtolower($menu['link_title']) == 'corporate') $active = 'active';
		//print $arg1; exit;
		$submenu = '';
		if (strtolower($menu['link_title'])=='corporate' || strtolower($menu['link_title'])=='fragrance'
		|| strtolower($menu['link_title'])=='skin care' || strtolower($menu['link_title'])=='make up'
		|| strtolower($menu['link_path'])=='news_event') {
			if (strtolower($menu['link_title'])=='corporate') {
				$submenu = '<ul class="sub-nav">';
				$query = "SELECT nid, title FROM node WHERE type='corporate'";
				$result = db_query($query);
				foreach($result as $row) {
					$alias = drupal_lookup_path('alias',"node/".$row->nid);
					$submenu .= '<li><a href="'.$base_url.'/'.$alias.'" title="'.$row->title.'">'.$row->title.'</a></li>';
				}
				$submenu .= '</ul>';
			} else if (strtolower($menu['link_title'])=='fragrance') {
				$submenu = _generate_product_submenu('fragrance');
			} else if (strtolower($menu['link_title'])=='skin care') {
				$submenu = _generate_product_submenu('skin_care');
			} else if (strtolower($menu['link_title'])=='make up') {
				$submenu = _generate_product_submenu('make_up');
			}	else if (strtolower($menu['link_path'])=='news_event') {
				$submenu = '<ul class="sub-nav"><li><a href="'.$base_url.'/press_coverage" title="Press Coverage">Press Coverage</a></li></ul>';
			}
			
			if ($menu['link_path'] == 'corporate') $menu_link_path = '#';
			else $menu_link_path = $base_url.'/'.$menu['link_path'];
			$output .= '
				<li class="menu-item-has-children '.$active.'"><span class="open-subnav"></span>
					<a href="'.$menu_link_path.'">'.$menu['link_title'].'</a>
					'.$submenu.'
				</li>';
		} else {
			if (strtolower($menu['link_title']) == 'home') $link_path = '';
			else $link_path = $menu['link_path'];
			$output .= '<li class="menu-item-has-children '.$active.'"><a href="'.$base_url.'/'.$link_path.'">'.$menu['link_title'].'</a></li>';	
		}
	}
	return $output;
}

function _generate_product_submenu($product_type) {
	global $base_url;
	$submenu = '<ul class="sub-nav">';
	$categories = get_product_category($product_type);
	foreach($categories as $category) {
		$submenu .=	'<li><a href="'.$base_url.'/'.$product_type.'/'.$category->tid.'" title="'.$category->tid.'">'.$category->name.'</a></li>';
	}
	$submenu .= '</ul>';
	
	return $submenu;
}
?>
