<?php

// $Id$
function cnf_admin_page_menu() {
	// custom page other setting
	$items['admin/other_setting'] = array(
		'title' => t('Other Setting'),
		'description' => 'other setting',
		'page callback' => 'other_setting',
		'access arguments' => array('access other setting'),
		'type' =>  MENU_CALLBACK,
	);
	return $items;
}

/**
* Implements hook_permission().
*/
function cnf_admin_page_permission() {
  return array(
    'access other setting' => array(
      'title' => t('Access other setting for admin'),
    ), 
  );
}

/* 
 -------------------------------------------------------------------------------------------------------------------------
 * START OTHER SETTING 
 ------------------------------------------------------------------------------------------------------------------------- 
 */

function other_setting_form($form, &$form_state) {
	$form['contact_email1'] = array(
			'#type' => 'textfield', 
			'#title' => 'Contact Email 1',
			'#required' => true,
			'#default_value' => variable_get('contact_email1'),
	);
	$form['contact_email2'] = array(
			'#type' => 'textfield', 
			'#title' => 'Contact Email 2',
			'#default_value' => variable_get('contact_email2'),
	);
	$form['contact_email3'] = array(
			'#type' => 'textfield', 
			'#title' => 'Contact Email 3',
			'#default_value' => variable_get('contact_email3'),
	);
	$form['contact_email4'] = array(
			'#type' => 'textfield', 
			'#title' => 'Contact Email 4',
			'#default_value' => variable_get('contact_email4'),
	);
	$form['contact_email5'] = array(
			'#type' => 'textfield', 
			'#title' => 'Contact Email 5',
			'#default_value' => variable_get('contact_email5'),
	);
	$form['contact_text'] = array(
			'#type' => 'textfield', 
			'#title' => 'Contact Text',
			'#type' => 'text_format',
			'#default_value' => variable_get('contact_text'),
	);
	$form['career_email1'] = array(
			'#type' => 'textfield', 
			'#title' => 'Career Email 1',
			'#required' => true,
			'#default_value' => variable_get('career_email1'),
	);
	$form['career_email2'] = array(
			'#type' => 'textfield', 
			'#title' => 'Career Email 2',
			'#default_value' => variable_get('career_email2'),
	);
	$form['career_email3'] = array(
			'#type' => 'textfield', 
			'#title' => 'Career Email 3',
			'#default_value' => variable_get('career_email3'),
	);
	$form['career_email4'] = array(
			'#type' => 'textfield', 
			'#title' => 'Career Email 4',
			'#default_value' => variable_get('career_email4'),
	);
	$form['career_email5'] = array(
			'#type' => 'textfield', 
			'#title' => 'Career Email 5',
			'#default_value' => variable_get('career_email5'),
	);
	$form['how_do_you_know_us'] = array(
			'#type' => 'textarea', 
			'#title' => 'How Do You Know Us',
			#'#type' => 'text_format',
			'#default_value' => variable_get('how_do_you_know_us'),
	);
	$form['office_address'] = array(
			'#type' => 'textfield', 
			'#title' => 'Office Address',
			'#type' => 'text_format',
			'#default_value' => variable_get('office_address'),
	);
	$form['twitter'] = array(
			'#type' => 'textfield', 
			'#title' => 'Twitter',
			'#default_value' => variable_get('twitter'),
	);
	$form['facebook'] = array(
			'#type' => 'textfield', 
			'#title' => 'Facebook',
			'#default_value' => variable_get('facebook'),
	);
	$form['youtube'] = array(
			'#type' => 'textfield', 
			'#title' => 'Youtube',
			'#default_value' => variable_get('youtube'),
	);
	$form['instagram'] = array(
			'#type' => 'textfield', 
			'#title' => 'Instagram',
			'#default_value' => variable_get('instagram'),
	);
	$form['submit'] = array(
			'#type' => 'submit', 
			'#title' => 'Submit',
			'#value' => 'Submit'
	);

	return $form;    
}

function other_setting_form_submit($form, &$form_state) {
	//print "<pre>".print_r($form['how_do_you_know_us']['value']['#value'], true)."</pre>"; exit;
	$contact_email1 = variable_set('contact_email1', $form['contact_email1']['#value']);
	$contact_email2 = variable_set('contact_email2', $form['contact_email2']['#value']);
	$contact_email3 = variable_set('contact_email3', $form['contact_email3']['#value']);
	$contact_email4 = variable_set('contact_email4', $form['contact_email4']['#value']);
	$contact_email5 = variable_set('contact_email5', $form['contact_email5']['#value']);
	$contact_text = variable_set('contact_text', $form['contact_text']['value']['#value']);
	$career_email1 = variable_set('career_email1', $form['career_email1']['#value']);
	$career_email2 = variable_set('career_email2', $form['career_email2']['#value']);
	$career_email3 = variable_set('career_email3', $form['career_email3']['#value']);
	$career_email4 = variable_set('career_email4', $form['career_email4']['#value']);
	$career_email5 = variable_set('career_email5', $form['career_email5']['#value']);
	$how_do_you_know_us = variable_set('how_do_you_know_us', $form['how_do_you_know_us']['#value']);
	$office_address = variable_set('office_address', $form['office_address']['value']['#value']);
	$twitter = variable_set('twitter', $form['twitter']['#value']);
	$facebook = variable_set('facebook', $form['facebook']['#value']);
	$youtube = variable_set('youtube', $form['youtube']['#value']);
	$instagram = variable_set('instagram', $form['instagram']['#value']);
	drupal_set_message("Save Successfully", "notice");
}

function other_setting() {
	$output = "<h1>Other Setting</h1>";
	$form = drupal_get_form('other_setting_form');
	$output .= drupal_render($form);

	return $output;
}

/* 
 -------------------------------------------------------------------------------------------------------------------------
 * END OTHER SETTING 
 ------------------------------------------------------------------------------------------------------------------------- 
 */

?>
